Mon Feb 05 09:02:53 SGT 2024 : Apache Derby Network Server - 10.10.2.0 - (1582446) started and ready to accept connections on port 1527
----------------------------------------------------------------
Mon Feb 05 09:02:54 SGT 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): instance a816c00e-018d-76ca-1d35-ffffbf630b57 
on database directory C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System\HRPayrollSystemDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a 
Loaded from file:/C:/Users/xiuha/OneDrive/Desktop/DCOMS/Tutorial/04-T4/db-derby-10.10.2.0-lib/db-derby-10.10.2.0-lib/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11.0.14+8-LTS-263
user.dir=C:\Users\xiuha\OneDrive\Desktop\DCOMS\Tutorial\04-T4\db-derby-10.10.2.0-lib\db-derby-10.10.2.0-lib
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Feb 05 09:02:57 SGT 2024:
Shutting down instance a816c00e-018d-76ca-1d35-ffffbf630b57 on database directory C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System\HRPayrollSystemDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a 
Mon Feb 05 09:02:57 SGT 2024 Thread[DRDAConnThread_3,5,main] (DATABASE = HRPayrollSystemDB), (DRDAID = {2}), Database 'HRPayrollSystemDB' shutdown.
----------------------------------------------------------------
Mon Feb 05 09:03:12 SGT 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): instance 560740aa-018d-76ca-1d35-ffffbf630b57 
on database directory C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System\HRPayrollSystemDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a 
Loaded from file:/C:/Users/xiuha/OneDrive/Desktop/DCOMS/Tutorial/04-T4/db-derby-10.10.2.0-lib/db-derby-10.10.2.0-lib/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11.0.14+8-LTS-263
user.dir=C:\Users\xiuha\OneDrive\Desktop\DCOMS\Tutorial\04-T4\db-derby-10.10.2.0-lib\db-derby-10.10.2.0-lib
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System
Database Class Loader started - derby.database.classpath=''
Mon Feb 05 09:04:52 SGT 2024 Thread[DRDAConnThread_3,5,main] (XID = 231), (SESSIONID = 2), (DATABASE = HRPayrollSystemDB), (DRDAID = {4}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon Feb 05 09:04:52 SGT 2024 Thread[DRDAConnThread_3,5,main] (DATABASE = HRPayrollSystemDB), (DRDAID = {4}), Connection authentication failure occurred.  Reason: Invalid authentication..
----------------------------------------------------------------
Mon Feb 05 09:05:27 SGT 2024: Shutting down Derby engine
----------------------------------------------------------------
Mon Feb 05 09:05:27 SGT 2024:
Shutting down instance 560740aa-018d-76ca-1d35-ffffbf630b57 on database directory C:\Users\xiuha\OneDrive\Desktop\DCOMS\Assignment\HR_Payroll_System\HR_Payroll_System\HRPayrollSystemDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a 
----------------------------------------------------------------
